syntax = "proto3";
package ratelimiter;

option go_package = "github.com/timskillet/rate-limiter-service/api";

service RateLimiter {
  rpc CheckRateLimit (CheckRequest) returns (CheckResponse);
  rpc UpdateLimits (UpdateLimitsRequest) returns (UpdateLimitsResponse);
}

message CheckRequest {
  string client_id = 1;
}

message CheckResponse {
  bool allowed = 1;
  int32 remaining = 2;
  int64 reset_at = 3;
}

message UpdateLimitsRequest {
  string client_id = 1;
  int32 rate = 2;
  int32 burst = 3;
}

message UpdateLimitsResponse {
  bool success = 1;
} 